### ISSUE TITLE
OpenTok.CreateSession throwing object reference exception

### ISSUE THREAD

**Issue by panther008** [opentok/Opentok-.NET-SDK#106]
Hi
I have implemented open tok in my .net project every thing was working fine until today as opentok.create session() is giving me object reference error.Please guide ASAP.I am using  Newtonsoft.Json = 10.0.2
nuget JWT = 2.3.2 
nuget OpenTok = 2.4.7

**Comment by msach22** [comment]
@panther008 @timophy We disabled support for TLS 1.0 yesterday which is what your issue looks like. 
Can you please confirm you're not using TLS 1.0 on your production environment?

You can also force TLS1.2 by doing the following:
`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12`

**Comment by timophy** [comment]
@msach22 That fixed it for me. Thanks!

**Comment by msach22** [comment]
@timophy happy to help!

**Comment by panther008** [comment]
yes issue is fixed. thanks for help.
