### ISSUE TITLE
Paused Minutes in Archive Duration

### ISSUE THREAD

**Issue by ratanosian** [opentok/Opentok-.NET-SDK#107]
A few months ago, you started including Paused Minutes in the Duration field of the Archive object.  Since then, the Duration has not matched the actual length of the Archived Video.  If I look at the Archive Inspector tool, there is a Running Minutes field that shows the correct video length.  I believe you should either correct the Duration field so it only includes Running Minutes, or you should provide a new field that provides the Running Minutes for the Archive object.

**Comment by msach22** [comment]
@ratanosian Could you please contact support@tokbox.com and share the Archive ID with them where you're not seeing the duration field match the length of the archive. 

This does not seem like an issue with the .NET SDK instead with the Archiving functionality.

**Comment by ratanosian** [comment]
I already have been in touch with Tokbox support (https://support.tokbox.com/hc/en-us/requests/22980) and they told me to open an Issue here. 

If you look at an Archive in the Archive Inspector, there are 4 times available:
**Meeting Duration**
**Archive Duration** <- This is the Duration field reported by the .NET SDK
**Running Minutes** <- This is the actual length of the archived video file, the only number that I actually care about, but is not available in the .NET SDK
**Paused Minutes**

Here are some recent examples where the Duration doesn't match the length of the video file.

ArchiveID: 09789cfb-c98c-4c64-911b-1dd8232b1c8b
Created At: Aug 18, 2018 09:34:33AM
TokBox Archive Duration: 16:32
Actual File Duration (Running Min): 15:26
Azure Archive: https://tokboxd.blob.core.windows.net/atlas-video/45614802/09789cfb-c98c-4c64-911b-1dd8232b1c8b/archive.mp4

Most of them seem to add about 1 min to the Duration, but this one is over 7 min difference:

ArchiveID: 4ad48bbc-28bd-4778-8b43-f0444f6de870
Created At: Aug 17, 2018 02:58:00PM
TokBox Archive Duration: 36:04
Actual File Duration (Running Min): 29:01
Azure Archive: https://tokboxd.blob.core.windows.net/atlas-video/45614802/4ad48bbc-28bd-4778-8b43-f0444f6de870/archive.mp4

This one is an empty file that still shows a Duration:  

ArchiveID: d7edb6a0-b8ea-4f06-b7b6-107b7303940d
Created At: Aug 17, 2018 05:34:29PM
TokBox Archive Duration: 3:24
Actual File Duration (Running Min): 0:00
Azure Archive: https://tokboxd.blob.core.windows.net/atlas-video/45614802/d7edb6a0-b8ea-4f06-b7b6-107b7303940d/archive.mp4

**Comment by ratanosian** [comment]
Is there any update on this?  Basically I just need a way to get the Running Minutes field from the SDK.  Is this possible or can it be added?

**Comment by ratanosian** [comment]
Please respond.  I am still waiting on a way to get Running Minutes.

**Comment by ratanosian** [comment]
Still no response.  I am reopening a support ticket.  Being able to access Running Minutes should not be difficult.

**Comment by msach22** [comment]
@ratanosian Apologies for the delayed response! Unfortunately, we are unable to provide the `running minutes` field as a part of the .NET SDK because it's not a part of the API response: https://tokbox.com/developer/rest/#start_archive. 

This is something that is calculated manually by the Archive Inspector tool. To achieve this, you would have to do your own calculations.

**Comment by msach22** [comment]
@ratanosian I'm going to go ahead and close this issue, please let me know if you have any questions!

**Comment by msach22** [comment]
@ratanosian At this time, we use internal APIs to calculate the running minutes. Unfortunately, at this time, we do not have a mechanism in place to expose those APIs. I've forwarded your request to our product team and will update you as soon as I have more information.

**Comment by PK1NONLY** [comment]
is there any update on this??

**Comment by msach22** [comment]
@PK1NONLY No update on this yet, we do not have a mechanism in place to expose APIs to calculate the running minutes.
