### ISSUE TITLE
CreateSession fails at app start.

### ISSUE THREAD

**Issue by MenaceSan** [opentok/Opentok-.NET-SDK#123]
CreateSession fails at app start.
Must configure your app to use only TLS 1.2
as of 6/6/19 the OpenTok .NET samples are broken unless you make this change.

OpenTok /.NET samples
https://github.com/opentok/Opentok-.NET-SDK

add to OpenTokService.cs:
System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12

Create a demo account . make changes to the app.config for you API_KEY and API_SECRET
HellowWorld sample project will fail with "System.Net.Sockets.SocketException: 'An existing connection was forcibly closed by the remote host'" deep in the CreateSession Call.
in CreateSession -> Post -> DoRequest -> SendData ->SetRequestStream and then about 22 more stack levels down.

related to:
https://stackoverflow.com/questions/51659216/opentok-createsession-error-with-request-submission

**Comment by abidCharlotte49er** [comment]
I have set SecurityProtocol to Tls12 it still fails. I have tried all 5 param combinations I can pass. What am I missing ? 
 
![image](https://user-images.githubusercontent.com/2357276/62656000-41346680-b931-11e9-879c-d8882a3be49d.png)

**Comment by abidCharlotte49er** [comment]
I have also tried with the OpenTok's sample app, added security protocol as seen in the image. I'm still can't create session, getting same error like I'm getting in my application. @MenaceSan  @msach22  any updates on this are much appreciated.  Currently we hit the rock bottom with this error, Please help!!!

at OpenTokSDK.Util.HttpClient.DoRequest(String url, Dictionary`2 specificHeaders, Dictionary`2 bodyData) in \GithubProjects\Opentok-.NET-SDK\OpenTok\Util\HttpClient.cs:line 137 
at OpenTokSDK.Util.HttpClient.Post(String url, Dictionary`2 headers, Dictionary`2 data) in \GithubProjects\Opentok-.NET-SDK\OpenTok\Util\HttpClient.cs:line 63 
at OpenTokSDK.OpenTok.CreateSession(String location, MediaMode mediaMode, ArchiveMode archiveMode) in \GithubProjects\Opentok-.NET-SDK\OpenTok\OpenTok.cs:line 159 
at HelloWorld.OpenTokService..ctor() in \GithubProjects\Opentok-.NET-SDK\Samples\HelloWorld\OpenTokService.cs:line 54

![image](https://user-images.githubusercontent.com/2357276/62777342-3d146000-ba7b-11e9-95b9-19f0a50c0913.png)

**Comment by abidCharlotte49er** [comment]
Additional details related to exception. You can see the Protocol is set to Tls12 in the watch window. "The remote server returned an error: (403) Forbidden." Not sure why i'm getting forbidden error. I can confirm I'm copying these key and secret I see on my dashboard.     

![image](https://user-images.githubusercontent.com/2357276/62787370-91770a00-ba92-11e9-9b2b-73b573465c99.png)


![image](https://user-images.githubusercontent.com/2357276/62786703-25e06d00-ba91-11e9-95f8-df268e62e979.png)

**Comment by msach22** [comment]
@MenaceSan Could you please check that the JWT token that your server is generating is not expired and is valid? The Server SDK generates the JWT token, but if your application server clock is out of sync there can be issues on the expiration. You can check the token validation and expiration on jwt.io

**Comment by abidCharlotte49er** [comment]
@msach22 @MenaceSan That was it. I always set my clock few minutes ahead to troubleshoot things at our end. I understand how JWT token generated with that can cause this issue. There is absolutely no way I could have figured this issue without your inputs. Thank You so much really appreciate your time on this.

**Comment by msach22** [comment]
Happy to help @abidCharlotte49er 😄

**Comment by slorello89** [comment]
Fyi - the tls1.2 setting in the samples is going to be resolved by #125

**Comment by slorello89** [comment]
Closing out this item as it has been resolved by #125
