### ISSUE TITLE
ScreenSharing with System Audio

### ISSUE THREAD

**Issue by qzzf1w** [opentok/Opentok-.NET-SDK#124]
I am looking to share my screen (which I can do) and share system audio.

Their is no concept of audioprovider that I can see.
Just a boolean flag which picks up the default mic.

Is it possible to extend the SDK to achieve my goal?

**Comment by slorello89** [comment]
Hi @qzzf1w - pretty sure this is not related to the server SDK - can you find us in the Vonage Developers community slack so we can discuss? https://developer.nexmo.com/community/slack

thanks!
