### ISSUE TITLE
403 Forbidden with Sample HelloWorld

### ISSUE THREAD

**Issue by justlearntutors** [opentok/Opentok-.NET-SDK#132]
We can't make the sample HelloWorld work. We get 403 Forbidden error.

**Comment by slorello89** [comment]
@justlearntutors - a 403 points to an invalid api_key or web token see - https://tokbox.com/developer/rest/#session_id_production can you check that your credentials are set correctly. If your certain they are please contact support@nexmo.com - they are going to be able to point you in the right direction

**Comment by slorello89** [comment]
I think this is not an SDK issue so I'm going to close it out - please feel free to reopen if it persists.
