### ISSUE TITLE
layoutType and stylesheet not implemented for CreateArchive 

### ISSUE THREAD

**Issue by ababutski** [opentok/Opentok-.NET-SDK#145]
The OpenTok REST API provides layoutType selection and custom stylesheet for сomposed archives
https://tokbox.com/developer/rest/#start_archive
But .Net SDK doesn't have such options.

**Comment by slorello89** [comment]
Hi @ababutski thanks for writing in, I've opened #146 to resolve this.

**Comment by slorello89** [comment]
Hi @ababutski - This issue is resolved per [v3.4.0](https://www.nuget.org/packages/OpenTok/3.4.0). Closing this out - let us know if you run into any other issues.
