### ISSUE TITLE
why is Session.Id a string while Archive.Id a Guid?

### ISSUE THREAD

**Issue by aoberoi** [opentok/Opentok-.NET-SDK#29]

**Comment by aoberoi** [comment]
the fact is that session IDs are not `Guid` formatted strings. this incongruence is an eye sore. i don't see any real advantage of using a `Guid` for the `Archive.Id`, so one proposal is to just change it to a `string`. this would require a major version bump.

**Comment by matt-lethargic** [comment]
Reading through the documentation shows that the `Broadcast` and `Session` IDs are random strings while the `Archive` ID is in fact a `GUID` for this reason I see no reason to change `Archive.Id` to a string.
