### ISSUE TITLE
organize unit tests better

### ISSUE THREAD

**Issue by aoberoi** [opentok/Opentok-.NET-SDK#43]
there's only one test Class right now: `OpenTokTest`. There should be another one to test the API for Archives named `ArchiveTest`, and possibly even `ArchiveListTest`. it should be as DRY as possible so the common method tests should ideally only be implemented once.

**Comment by aoberoi** [comment]
also, the request bodies are not currently tested.

**Comment by matt-lethargic** [comment]
Closing due to age
