### ISSUE TITLE
Xamarin Support on nuget

### ISSUE THREAD

**Issue by NVentimiglia** [opentok/Opentok-.NET-SDK#62]
This library is fully compatible with Xamarin projects. Please update the nuget package to support Xamarin IOS and Android projects so we can import this project directly using nuget.... and not have to copy and paste the code into our project. manually...

**Comment by aoberoi** [comment]
@NVentimiglia: we don't recommend using the server SDKs in client applications (iOS and Android). Unless you have some very special circumstances, that's usually a bad way to build you app. The server SDK needs access to your API Secret, and shipping that in a client application is very tricky to do without compromising security. You typically use this package to create a web service that your client application will communicate with.

**Comment by NVentimiglia** [comment]
That is a fair point, I will put this on the server.
