### ISSUE TITLE
Request for Screensharing Application using .net Libraries

### ISSUE THREAD

**Issue by Raj123456788** [opentok/Opentok-.NET-SDK#69]
Hello There,
               I am looking for a cross-platform solution that would capture the screen,
Encode(VP8) &amp; stream desktop @ 1080p , 30 fps.May I please request for sample app on screensharing crossplatform desktop apps showing 30fps?

Also, does open tok SDK supports streaming of Audio on Android. 

Thanks,
Raj

**Comment by aullman** [comment]
This is not the right place for this kind of question. This repository is specifically for the OpenTok .net SDK and any issues/questions related to that project.
