### ISSUE TITLE
OpenTokException does not expose InnerException

### ISSUE THREAD

**Issue by shaunbowe** [opentok/Opentok-.NET-SDK#70]
We have intermittent errors scheduling interviews with OpenTok and all we see is "Error with request submission". Is there a reason the exception parameter is not passed to System.Exception as the InnerException? It would be helpful to debug intermittent errors.

**Comment by aullman** [comment]
Good question. I don't see a strong reason why not. Please feel free to submit a PR.

**Comment by matt-lethargic** [comment]
Closing.
