### ISSUE TITLE
HelloWorld Sample does not work in 2 windows

### ISSUE THREAD

**Issue by rmenezes** [opentok/Opentok-.NET-SDK#71]
Hi
I'm having a problem with the HelloWorld sample, when I open more than one window, the others do not load the new frame. I had this problem developing a personal project and the same happened with the sample taken here.

![capturar](https://cloud.githubusercontent.com/assets/1154679/20632387/3d819b68-b324-11e6-9fc2-4369be770072.PNG)

Can anybody help me?
Thanks!

**Comment by aullman** [comment]
I'm guessing this is because it's using a really old version of opentok.js
