### ISSUE TITLE
OpenTok.ListArchives() does not support filtering by session ID

### ISSUE THREAD

**Issue by jeffswartz** [opentok/Opentok-.NET-SDK#73]
The OpenTok REST API now lets you filter by session ID when getting a list of archives: https://tokbox.com/developer/rest/#listing_archives. (You pass in a `sessionId` query parameter when calling the REST API method.) The `OpenTok.ListArchives()` methods in the OpenTok .NET server SDK does not support this session ID filter.

**Comment by matt-lethargic** [comment]
Closing as resolved with #143
