### ISSUE TITLE
Showing participant's name along with their stream

### ISSUE THREAD

**Issue by prabhakarreddy1234** [opentok/Opentok-.NET-SDK#86]
Is there anyway to display participant's name along with the stream in a group video conference ? I am just seeing 2 `div`s in the html. Not sure if we can customize it.

**Comment by aullman** [comment]
Yes, if you pass a name property to the publisher when you create it then that name will appear on all of the subscribers to that publisher.

```
OT.initPublisher(elementId, {
  name: 'MyName'
});
```

More details at https://tokbox.com/developer/sdks/js/reference/OT.html#initPublisher
