### ISSUE TITLE
CreateSession exception

### ISSUE THREAD

**Issue by uchetto** [opentok/Opentok-.NET-SDK#91]
Hello everyone,
I'd like to know why this code is not ok. When i run it an exception is raised on CreateSession method. 
The error is:

"Error with request submission"        

I checked the apikey and secret key and they are ok.

This also happens with the demo solution.

Thanks in advance....

Here is the code:

Dim opentok As New OpenTok(API_KEY, API_SECRET)
        Dim opentokSession As Session

        Try
            opentokSession = opentok.CreateSession(MediaMode.ROUTED)

            SESSIOID = opentokSession.Id
            ' Replace with meaningful metadata for the connection.
            Dim connectionMetadata As String = "username=Bob,userLevel=4"

            ' Generate a token. Use the Role value appropriate for the user.
            TOKEN = opentok.GenerateToken(SESSIOID, Role.PUBLISHER, Nothing, connectionMetadata)
        Catch ex As System.Exception
            Dim a As String

            a = ex.ToString

            'Catch ex As OpenTokException
            '    Dim a As String

            '    a = ex.ToString

        End Try

**Comment by aiham** [comment]
@uchetto Can you enable debug mode?

```
var OpenTok = new OpenTok(apiKey, apiSecret);
OpenTok.Debug = true;
``

You will see the full request and response details in the console logs. If you feel there is nothing sensitive in these logs, then can you please paste them here? If they have sensitive information then please redact the sensitive parts or create a support ticket to contact support directly.

**Comment by aiham** [comment]
Make sure you don't keep debug mode turned on in a production environment.

**Comment by uchetto** [comment]
Thank you, I tried, but no more information about exception
This is the text of error:

'OpenTokSDK.Exception.OpenTokWebException' in OpenTok.dll

The stack trace:

"   in OpenTokSDK.Util.HttpClient.DoRequest(String url, Dictionary`2 specificHeaders, Dictionary`2 bodyData)" & vbCrLf & "   in OpenTokSDK.Util.HttpClient.Post(String url, Dictionary`2 headers, Dictionary`2 data)" & vbCrLf & "   in OpenTokSDK.OpenTok.CreateSession(String location, MediaMode mediaMode, ArchiveMode archiveMode)" & vbCrLf & "   in _Default.form1_PreRender(Object sender, EventArgs e) in C:\inetpub\wwwroot\videochatTest\Default.aspx.vb:riga 43"

Only this, no other message.

My application is an asp.net application. What's wrong?

**Comment by uchetto** [comment]
This is a screenshot of example application HelloWorld. I obtain the same error. During CreateSession the error was generated at this line of CreateSession:

var response = Client.Post("session/create", headers, data);

![image](https://user-images.githubusercontent.com/16920233/30379158-dad50a10-9895-11e7-894a-4c680585b6ba.png)

Can you help me? I cannot understand why it happens.

Thank you...

**Comment by aiham** [comment]
@uchetto You received an `Issuer not found` error. This is because you are using your account ID which begins with 3. You need to use your project ID which begins with 4.

**Comment by uchetto** [comment]
Excuse me, i don't understand..I have apikey and secretkey. What is account ID?
Thanks for reply

**Comment by uchetto** [comment]
Ahhhhhh, I understand now. I generated apikey and apisecret for an embedded project and not for opentok api project.

Thank you so muchhhhhhh!!!!
