### ISSUE TITLE
outputMode.ToString().ToLower() generates invalid data if called within Turkish Culture settings

### ISSUE THREAD

**Issue by lvass74** [opentok/Opentok-.NET-SDK#92]
https://github.com/opentok/Opentok-.NET-SDK/blob/6cede8d6867e9542b624241122b02070128b278b/OpenTok/OpenTok.cs#L270

Dear Opentok Developers,

We recently faced a very annoying issue where our StartArchive called resulted in a ""The request was aborted: The request was canceled." exception for clients in Turkey.

After multiple days of debugging we found out that it was not related with Turkey as a country rather Turkish being the preferred language in the browser of the affected clients.
It turned out that converting the enum "INDIVIDUAL" to lower case string usually results in a string "individual" - as expected - however when .NET is running with culture "tr-TR" the result of this operation is "ındıvıdual" (please not the "i" characters without a dot on top!). This is because in the Turkish language there are two different "i" character one with dot on top and one without both having there upper case versions. As a result converting the upper case latin i character (that has not dot on top) results in Turkish culture in a lower case "ı" character (i without a dot on top) that later provokes an exception ("Cannot close stream until all bytes are written.") being thrown at https://github.com/opentok/Opentok-.NET-SDK/blob/master/OpenTok/Util/HttpClient.cs#L147 upon stream.Write.

In our case the issue appeared because in our Web.config we had the following value:
    <globalization uiCulture="auto" **culture="auto"** enableClientBasedCulture="true" />

As your SDK may be used in such environment I suggest to apply a fix that is straightforward and of very low risk in my opinion. The fix would be to change:
outputMode.ToString().ToLower()
to
outputMode.ToString().ToLowerInvariant() 

That way the conversion will be independent of any application level culture settings and will always result the expected "individual" string.

Best Regards,

---
Laszlo Vass
Web developer
laszlo.vass@realeyesit.com | realeyesit.com

**Comment by aiham** [comment]
Thanks for tracking down this issue @lvass74! I was actually in discussion with Charley and others about your issue and it was very confusing. Really great to hear an explanation for that strange behaviour. I'll work on this fix right away.

**Comment by lvass74** [comment]
Thanks for the quick reaction and the fix!
