### ISSUE TITLE
archive model has no password attribute

### ISSUE THREAD

**Issue by kayhuba** [opentok/Opentok-.NET-SDK#94]
The class OpenTokSDK.Archive does not contain a "Password" field. This field is required when retrieving information about an encrypted archive. See https://static.opentok.com/developer/enterprise/content/OpenTok-encryption/#decrypting-an-archive

Since the REST API call returns the JSON attribute already, the change is minimal.

**Comment by aiham** [comment]
@kayhuba Thank you!
