### ISSUE TITLE
raw audio buffers

### ISSUE THREAD

**Issue by unicomp21** [opentok/Opentok-.NET-SDK#96]
How do I get access to the raw audio buffer?

**Comment by aiham** [comment]
Hi @unicomp21. If you want access to the audio streamed in a session you'll either need to connect to a session using a client SDK (Web/Mobile/Desktop) and access the audio track or you can download an archive of the session and process the video file yourself. You can use the .NET SDK to retrieve the URL of your archive file but it does not have access to any audio buffers. Does that answer your question?
