### ISSUE TITLE
.NET Core compatible?

### ISSUE THREAD

**Issue by SwintDC** [opentok/Opentok-.NET-SDK#97]
Is this library .NET Core compatible? Or is there a .NET Core compatible version of this library?

There is some confusion because there is a .NET Core Cli command to install this library on https://www.nuget.org/packages/OpenTok. But this website https://icanhasdot.net says it's not supported.

**Comment by MelnikovIG** [comment]
@msach22 Hey, is there any chance that this package will be updated to modern net standard? Referenced JWT and Newtonsoft.Json libraries has support net standard long time ago.

**Comment by msach22** [comment]
Yes, we do plan on adding support for .NET Core, but unfortunately I don't have a timeline for that just yet.

**Comment by pratik1509** [comment]
core nuget package does not have methods for Sending Signal.

**Comment by msach22** [comment]
@pratik1509 The .NET Core package is not supported by us so I'm afraid we're unable to do anything about that. I'll update this issue once I have a definite timeline on adding official support for .NET Core

**Comment by jez9999** [comment]
This is slightly beyond belief.  .NET Core has been out for years and you guys still don't have a package that supports it?!  This one is pretty useless for new web apps!

**Comment by ErikAndreas** [comment]
Nuget [package](https://www.nuget.org/packages/OpenTokNetStandard/) for .Net Standard 2 but it only implements the CreateSession and GenerateToken methods (PR's welcome!). Rather "modern" (used with Azure Functions) and lightweight. Disclaimer: author of package

But, modern official support for .Net would have been nice!

**Comment by AresDev** [comment]
> Yes, we do plan on adding support for .NET Core, but unfortunately I don't have a timeline for that just yet. I'm happy to accept any PRs if anyone wants 😄

Any news?

**Comment by omerciftcibasi** [comment]
@AresDev I am able to create sessions on .net core, however I am getting signal "error with request submission" error while sending signal on Server. Is is something related to that your are not supporting .net core?

**Comment by slorello89** [comment]
Version 3.2.0 adds a new path for .net standard 2.0 so the sdk is now compatible with .NET Core. Big shout out to @danikun for making it happen.
