### ISSUE TITLE
CreateSession() Failing with JWT 4.0.0.0

### ISSUE THREAD

**Issue by aatobaa** [opentok/Opentok-.NET-SDK#98]
The OpenTok NuGet Package states that it accepts JWT versions >= 2.3.2 but fails when the assembly contains a reference to version 4.0.0.0.

Exception: Could not resolve type with token 0100004b (from typeref, class/assembly JWT.IJwtAlgorithm, JWT, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null)

Stack trace: 
at OpenTokSDK.Util.HttpClient.GetCommonHeaders () [0x00005] in <85a76a4b5d324419bd872ebb6c385070>:0 at OpenTokSDK.Util.HttpClient.GetRequestHeaders (System.Collections.Generic.Dictionary`2[TKey,TValue] headers) [0x00000] in <85a76a4b5d324419bd872ebb6c385070>:0 at OpenTokSDK.Util.HttpClient.DoRequest (System.String url, System.Collections.Generic.Dictionary`2[TKey,TValue] specificHeaders, System.Collections.Generic.Dictionary`2[TKey,TValue] bodyData) [0x00009] in <85a76a4b5d324419bd872ebb6c385070>:0 at OpenTokSDK.Util.HttpClient.Post (System.String url, System.Collections.Generic.Dictionary`2[TKey,TValue] headers, System.Collections.Generic.Dictionary`2[TKey,TValue] data) [0x00010] in <85a76a4b5d324419bd872ebb6c385070>:0 at OpenTokSDK.OpenTok.CreateSession (System.String location, OpenTokSDK.MediaMode mediaMode, OpenTokSDK.ArchiveMode archiveMode) [0x00093] in <85a76a4b5d324419bd872ebb6c385070>:0 at OURPROJECT.Helpers.OpenTokHelper.CreateSession () [0x00015]

**Comment by duenwaldd1** [comment]
This was my error: 
"
Method not found: 'Void JWT.JwtEncoder..ctor(JWT.IJwtAlgorithm, JWT.IJsonSerializer, JWT.IBase64UrlEncoder)'.
"

Thank you for pointing out it was caused by JWT 4.0.0,
I downgraded to 3.1.1 and now it's all working again!

**Comment by gadeweever** [comment]
Hey so I'm getting the same error. I don't know that downgrading is a solution here if we have another assembly dependent on JWT 4.0.0. But also so others don't run into this issue in the future, the nuget package should specify that it is incompatible with JWT 4.0.0 and, since that is the current version, the default experience for including OpenTok in a project is broken. 

Are there any plans to fix this?

**Comment by janoonaj** [comment]
No fix yet?

**Comment by Cereal-Killa** [comment]
Same story here.

**Comment by gadeweever** [comment]
@Cereal-Killa we actually decided to move this call to an isolated service outside of our project because downgrading was not acceptable. The service references 2.3.2 and only handles OpenTok features. This is a compromise but we don't have the bandwidth to invest in looking at the source yet.

**Comment by ababutski** [comment]
Same for us. But in our case we checked out opentok project from github and rebuild it for .Net Framework (4.7.2) with latest JWT package (5.3.1) and latest Newtonsoft.Json (12.0.3), that solved the problem. As a solution may be you can create different project version for different target framework.

**Comment by justlearntutors** [comment]
We have the same issue. Can the TokBox team fix the bug?

**Comment by slorello89** [comment]
The 3.2.0 version of the SDK has now been updated to pull in the latest version of JWT for all versions of .NET above .NET 4.6.2 so this should be resolved.

**Comment by Cereal-Killa** [comment]
.NET Framework 4.8 project here, no matter what I do the release 3.4.0 claims for JTW version 2.0.0.0:

`Could not load file or assembly 'JWT, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

**Comment by slorello89** [comment]
Hi @Cereal-Killa - I took the [Hello World](https://github.com/opentok/Opentok-.NET-SDK/tree/master/Samples/HelloWorld)  sample, bumped it to 4.8 and retargeted to JWT 7.2.1 - with no issue. Try reinstalling the packages and trying that.

If that doesn't work, if you could recreate the problem in a sample app you could point me to, and open a new Issue I'd be happy to take a look.
